### ISSUE TITLE
Configuration to use ObservableReturnValueHandler

### ISSUE THREAD

**Issue by fiunchinho** [jmnarloch/rxjava-spring-boot-starter#1]
Hi! Thank you for this repo.

I'm having issues trying to use it. My endpoint returns an Observable that emits two values, but I only see one of them in the browser. Trying to debug, I saw that it's always using the Bean for SingleReturnValueHandler(), and I guess ObservableReturnValueHandler() should be used instead. How can I get this working?

```
    @RequestMapping(path = "/users", method = RequestMethod.GET)
    public Observable<User> listUsers() {
        return myService.listUsers();
    }
```

**Comment by jmnarloch** [comment]
Hi,

The tests are covering such use case: https://github.com/jmnarloch/rxjava-spring-boot-starter/blob/master/src/test/java/io/jmnarloch/spring/boot/rxjava/mvc/ObservableReturnValueHandlerTest.java#L74 and https://github.com/jmnarloch/rxjava-spring-boot-starter/blob/master/src/test/java/io/jmnarloch/spring/boot/rxjava/Demo.java#L72

The rx.Single and rx.Observable does not share common ancestor and in terms of type their completely separated this way I don't understand why SingleReturnValueHandler might be used for handling Observable value.

Could consider sharing some sample project for debugging purpose?

Thanks

**Comment by fiunchinho** [comment]
My endpoint looks like

```
@RequestMapping(path = "/users", method = RequestMethod.GET)
    public Observable<User> listUsers() {
        return Observable.just(
                new User("abc", "John", "Doe"),
                new User("xyz", "Alice", "Wonderland")
        );
    }
```
So I was expecting both users to be on the response but I get only one
```
$ curl -i -XGET http://192.168.99.100:8002/users
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: reactive-response:8002
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Sat, 20 Feb 2016 16:11:01 GMT

{"id":"abc","name":"John","lastname":"Doe"}
```

Yes, I have last Spring Cloud version.
Maybe I'm miss understanding something?

**Comment by jmnarloch** [comment]
If you have Spring Cloud 1.1.M5 there is already defined a ObservableReturnValueHandler that will handle only single return values from Observable. Could you please verify that this is your case?

**Comment by fiunchinho** [comment]
Actually, I get the same behavior with and without your repository. These are my dependencies
![captura de pantalla 2016-02-20 a las 18 06 35](https://cloud.githubusercontent.com/assets/627038/13197969/d12e6d2c-d7fc-11e5-8670-6af22734a47c.png)

And I only get one the two Users on my Observable :sob:

**Comment by jmnarloch** [comment]
So your only option is to disable the Spring Clouds rx.Observable handler you should be able to do that through `@SpringBootApplication(exclude = RxJavaAutoConfiguration.class)`

**Comment by fiunchinho** [comment]
Thank you very much, that worked! But why? Shouldn't the ObservableReturnValueHandler in your library and the one in Spring both be equivalent?
Is there a way to get the same behavior using only Sprint without your library? It feels strange having this dependency and having to disable the RxJavaAutoConfiguration class.

**Comment by jmnarloch** [comment]
There being registered in Spring MVC and each time a handler return needs to be processed a AsyncHandlerMethodReturnValueHandler#supportsReturnType is being called. Looks like the Spring Cloud's had been registered prior the handler from this library and handled the value.

This project was basically a reference implementation, most of it's ideas are going to be included in Spring Cloud, hopefully by the release of 1.1.0.RELEASE.

**Comment by fiunchinho** [comment]
Althought Spring Cloud handler is registered prior the handler from this library, shouldn't both do exactly the same?

**Comment by jmnarloch** [comment]
In terms of implementation the one defined here will perform aggregation of the results using Observable.toList(), this ins't blocking operation, but requires that the Observable will end in some point in time. The Spring Cloud just takes the first result and discards any other results.

**Comment by fiunchinho** [comment]
I see. Thank you for your patience and your work.
